"use client"

import { createContext, useContext, useEffect, useMemo, useState } from "react"

type Lang = "en" | "ar"

const LanguageContext = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({ lang: "en", setLang: () => {} })
const DICTIONARY: Record<string, string> = {
  Services: "الخدمات",
  "Corporate Services": "خدمات الشركات",
  "Enterprise-grade On-Site Repair": "خدمة إصلاح ميداني بمستوى الشركات",
  Corporate: "الشركات",
  "Repair Solutions": "حلول الإصلاح",
  "Corporate hero description": "خدمات إصلاح احترافية وموثوقة لأجهزة الشركات — تُقدَّم مباشرة في موقع عملك داخل الإمارات.",
  "Priority SLA": "اتفاقية مستوى خدمة أولوية",
  "Guaranteed response times": "أوقات استجابة مضمونة",
  "Secure Handling": "تعامل آمن",
  "Data privacy compliant": "متوافق مع خصوصية البيانات",
  "Contract-Based": "عقود خدمة",
  "Flexible monthly plans": "خطط شهرية مرنة",
  "24/7 Ops": "تشغيل على مدار الساعة",
  "Critical infrastructure support": "دعم البنية التحتية الحساسة",
  "Request Partnership": "طلب شراكة",
  "Book Technician": "احجز فنيًا",
  Response: "الاستجابة",
  Techs: "الفنيون",
  "Devices/Mo": "جهاز/شهر",
  "Built for": "حل موثوق",
  "Critical Industries": "للقطاعات التي لا تحتمل الخطأ",
  "Critical industries description": "بنية إصلاح ميدانية متخصصة للقطاعات التي لا تحتمل التوقف.",
  "The entities we deal with": "الجهات التي نتعامل معها",
  "Comprehensive Device Support": "دعم شامل للأجهزة",
  "Mobile Fleet": "أسطول الأجهزة المحمولة",
  "iPhone – Samsung – Huawei – Tablets": "آيفون – سامسونج – هواوي – أجهزة لوحية",
  "Laptops & Workstations": "الحواسيب المحمولة ومحطات العمل",
  "Dell – HP – Lenovo – MacBook": "دل – إتش بي – لينوفو – ماك بوك",
  "Office Equipment": "معدات المكتب",
  "Printers – Scanners – Plotters": "طابعات – ماسحات – أجهزة رسم",
  "Displays & Signage": "الشاشات واللافتات",
  "Monitors – Video Walls – Kiosks": "شاشات – جدران فيديو – أكشاك",
  "Security Systems": "أنظمة الأمن",
  "CCTV – Access Control – Biometrics": "كاميرات – تحكم بالوصول – قياسات حيوية",
  "Meeting Rooms": "غرف الاجتماعات",
  "Smart TVs – Projectors – Audio": "تلفزيونات ذكية – عارضات – صوتيات",
  "Corporate Advantages": "مزايا الشركات",
  "Dedicated Account Manager": "مدير حساب مخصص",
  "Priority Service": "خدمة أولوية",
  "On-Site Repairs": "إصلاحات في الموقع",
  "Maintenance Contracts": "عقود صيانة",
  "Asset Reporting": "تقارير الأصول",
  "Data Security": "أمان البيانات",
  "Schedule a": "جدولة",
  "Corporate Technician": "فني شركات",
  "Corporate form description": "أكمل النموذج لطلب خدمة شركات ذات أولوية.",
  "Priority Support": "دعم أولوية",
  "Ready to Upgrade Your Corporate Maintenance?": "هل أنت مستعد لترقية صيانة شركتك؟",
  "Corporate CTA description": "نوفر خدمات إصلاح وصيانة في الموقع لعملاء الشركات وفق اتفاقية أولوية. جميع الإصلاحات ينفذها فنّيون معتمدون مع التزام كامل بخصوصية البيانات ومعايير الأمان.",
  "Get a Quote": "احصل على عرض",
  
  "24/7": "على مدار 24/7",
  "All UAE": "جميع أنحاء الإمارات",
  "Call Us (24/7)": "اتصل بنا (24/7)",
  "WhatsApp Support": "دعم واتساب",
  "Chat Instantly": "دردشة فورية",
  "Email Us": "راسلنا عبر البريد",
  "Trusted by": "موثوق من قبل",
  "Corporate Maintenance Contracts": "عقود صيانة للشركات",
  "Monthly Contract": "عقد شهري",
  "Unlimited visits": "زيارات غير محدودة",
  "Fixed monthly rate": "رسوم شهرية ثابتة",
  "Priority repairs": "أولوية في الإصلاح",
  "Yearly Contract": "عقد سنوي",
  "Discounted pricing": "أسعار مخفضة",
  "Full IT Support": "دعم تقني شامل",
  "Replacement options": "خيارات الاستبدال",
  "Pay-Per-Visit": "الدفع لكل زيارة",
  "One-time repair": "إصلاح مرة واحدة",
  "Standard rates": "أسعار قياسية",
  "Ideal for occasional needs": "مثالي للاحتياجات العرضية",
  "POPULAR": "شائع",
  "avg response": "متوسط الاستجابة",
  "Priority dispatch for corporate clients": "أولوية الإرسال لعملاء الشركات",
  "technicians": "فنيين",
  "Coverage across all UAE regions": "تغطية جميع مناطق الإمارات",
  "devices/month": "جهاز/شهر",
  "Enterprise-grade servicing capacity": "قدرة خدمة بمستوى الشركات",
  "Book Now": "احجز الآن",
  "Track Order": "تتبّع الطلب",
  About: "من نحن",
  Contact: "تواصل معنا",
  "Call Now": "اتصل الآن",
  "Call Us": "اتصل بنا",
  Menu: "القائمة",
  Navigation: "التنقل",
  "Support Chat": "دردشة الدعم",
  "We reply fast on WhatsApp": "نرد بسرعة عبر واتساب",
  "Chat with Support": "تواصل مع الدعم",
  "Open WhatsApp": "افتح واتساب",
  "Type your message...": "اكتب رسالتك...",
  "Hello, I want to book a technician.": "مرحبًا، أود حجز فني.",
  "Hello, I want to track my order.": "مرحبًا، أريد تتبّع طلبي.",
  "Hello, I need corporate support.": "مرحبًا، أحتاج دعم الشركات.",
  "Hello! I need support.": "مرحبًا! أحتاج إلى دعم.",
  "Corporate Support": "دعم الشركات",
  "Our Main Services": "خدماتنا الرئيسية",
  "Professional on-site repair services for all your devices": "خدمات إصلاح ميدانية احترافية لجميع أجهزتك",
  "Mobile Phone Repair": "إصلاح الهواتف المحمولة",
  "Laptop Repair": "إصلاح اللابتوب",
  "Printer Repair": "إصلاح الطابعات",
  "Monitor Repair": "إصلاح الشاشات",
  "PC / Desktop Computer Repair": "إصلاح أجهزة الكمبيوتر المكتبية",
  "TV Repair": "إصلاح التلفزيونات",
  "Apple Watch Repair": "إصلاح ساعة آبل",
  "CCTV Installation & Repair": "تركيب وإصلاح كاميرات المراقبة",
  "TV Wall Mounting": "تركيب التلفزيون على الحائط",
  "Gaming Console Repair": "إصلاح أجهزة الألعاب",
  "Services We Offer": "الخدمات المتاحة",
  "Brands We Service": "العلامات التجارية التي نخدمها",
  "Popular models we repair:": "نماذج شائعة نقوم بإصلاحها:",
  "+ many more": "+ المزيد",
  "Ready to Fix Your Device?": "هل أنت مستعد لإصلاح جهازك؟",
  "Book a technician now and get your device repaired at your doorstep. Fast, reliable, and guaranteed.": "احجز فنيًا الآن ليصل إليك ويصلح جهازك في موقعك. خدمة سريعة، موثوقة، ومضمونة.",
  "Book a Technician": "احجز فنيًا",
  "Ready to Get Your Device Fixed?": "هل أنت مستعد لإصلاح جهازك؟",
  "Skip the wait. Book a certified technician to come to your location today. Fast, reliable, and guaranteed.": "تجنّب الانتظار. احجز فنيًا معتمدًا ليأتي إلى موقعك اليوم. خدمة سريعة وموثوقة ومضمونة.",
  "WhatsApp Us": "تواصل عبر واتساب",
  "Contact Us": "تواصل معنا",
  "We're here to help! Reach out through any of the channels below or book a technician directly.": "نحن هنا لمساعدتك! تواصل عبر أي من القنوات أدناه أو احجز فنيًا مباشرةً.",
  "Service Area": "منطقة الخدمة",
  "We provide on-site repair services across all areas of Abu Dhabi, including:": "نقدّم خدمات إصلاح ميدانية في جميع مناطق أبوظبي، بما في ذلك:",
  "Service Hours": "ساعات الخدمة",
  "Saturday - Thursday": "السبت - الخميس",
  "Friday": "الجمعة",
  "Emergency Service": "خدمة الطوارئ",
  "24/7 Available": "متاح 24/7",
  "For urgent repairs outside regular hours, contact us via WhatsApp or phone for emergency service availability.": "للإصلاحات العاجلة خارج ساعات العمل، تواصل معنا عبر واتساب أو الهاتف لمعرفة توفر خدمة الطوارئ.",
  "Speak directly with our support team": "تحدث مباشرةً مع فريق الدعم",
  "Chat with us instantly": "تواصل معنا فورًا عبر الدردشة",
  "Send us an email anytime": "أرسل لنا بريدًا إلكترونيًا في أي وقت",
  "Send a message": "أرسل رسالة",
  "Why Choose KBI?": "لماذا تختار KBI؟",
  "We're committed to providing the best repair experience in Abu Dhabi": "ملتزمون بتقديم أفضل تجربة إصلاح في أبوظبي",
  "Professional Certified Technicians": "فنيون محترفون ومعتمدون",
  "Our team consists of trained and certified experts in device repair.": "فريقنا من خبراء مدرّبين ومعتمدين في إصلاح الأجهزة.",
  "Same-Day On-Site Service": "خدمة في الموقع في نفس اليوم",
  "We come to your location - home or office - on the same day you book.": "نصل إلى موقعك — المنزل أو المكتب — في نفس يوم الحجز.",
  "Free Diagnosis": "فحص مجاني",
  "Free diagnostic check when you approve the repair. No hidden fees.": "فحص تشخيصي مجاني عند الموافقة على الإصلاح. بدون رسوم مخفية.",
  "Original Spare Parts": "قطع غيار أصلية",
  "We use only genuine and high-quality replacement parts.": "نستخدم قطع غيار أصلية وعالية الجودة فقط.",
  "3-6 Months Warranty": "ضمان لمدة 3-6 أشهر",
  "All our repairs come with a solid warranty for peace of mind.": "جميع إصلاحاتنا بضمان قوي لراحة بالك.",
  "Transparent Pricing": "شفافية الأسعار",
  "Know the cost upfront. No surprises, no hidden charges.": "اعرف التكلفة مسبقًا. لا مفاجآت ولا رسوم مخفية.",
  "About Title Prefix": "عن",
  "About KBI": "عن KBI",
  "KBI is Abu Dhabi's trusted on-site repair service provider. We bring professional device repair directly to your doorstep - whether it's your home, office, or anywhere in Abu Dhabi.": "KBI هي مزوّد موثوق لخدمات الإصلاح الميداني في أبوظبي. نقدّم إصلاح الأجهزة بشكل احترافي مباشرةً إلى موقعك — سواء في المنزل أو المكتب أو أي مكان في أبوظبي.",
  "Years Experience": "سنوات من الخبرة",
  "Devices Repaired": "أجهزة تم إصلاحها",
  "Satisfaction Rate": "معدل الرضا",
  "Service Available": "الخدمة متاحة",
  "Who We Are": "من نحن",
  "Certified Technicians": "فنيون معتمدون",
  "Our technicians undergo rigorous training and certification programs to ensure they can handle any repair challenge. From the latest iPhone to gaming consoles, we've got you covered.": "يخضع فنّيونا لبرامج تدريب واعتماد صارمة لضمان التعامل مع أي تحدٍ في الإصلاح. من أحدث هواتف iPhone إلى أجهزة الألعاب، نحن جاهزون لخدمتك.",
  "Founded with a simple mission: to make device repair convenient and hassle-free. We understand how frustrating it can be when your phone, laptop, or TV breaks down unexpectedly.": "تم تأسيسنا برؤية بسيطة: جعل إصلاح الأجهزة مريحًا وخاليًا من التعقيد. ندرك مدى الإزعاج عندما يتعطل هاتفك أو لابتوبك أو تلفزيونك بشكل مفاجئ.",
  "That's why we created KBI - a mobile repair service that comes directly to you. Our team of certified technicians are equipped with the tools and expertise to fix most devices on the spot.": "لهذا أنشأنا KBI — خدمة إصلاح متنقلة تصل إليك مباشرةً. فريقنا من الفنيين المعتمدين مجهز بالأدوات والخبرة لإصلاح معظم الأجهزة في نفس المكان.",
  "We serve all areas of Abu Dhabi, including Al Reem Island, Khalifa City, Mohammed Bin Zayed City, Al Shamkha, and everywhere in between.": "نخدم جميع مناطق أبوظبي، بما في ذلك جزيرة الريم، مدينة خليفة، مدينة محمد بن زايد، الشامخة، وجميع المناطق فيما بينها.",
  "Each technician specializes in specific device categories:": "كل فني متخصص في فئات أجهزة محددة:",
  "Mobile phones & tablets (all brands)": "الهواتف المحمولة والأجهزة اللوحية (جميع العلامات)",
  "Laptops & computers (Windows & Mac)": "اللابتوبات وأجهزة الكمبيوتر (ويندوز وماك)",
  "TVs, monitors & home electronics": "التلفزيونات والشاشات والإلكترونيات المنزلية",
  "CCTV systems & security equipment": "أنظمة كاميرات المراقبة ومعدات الأمن",
  "Our Values": "قيمنا",
  "Our Mission": "مهمتنا",
  "To provide fast, reliable, and professional on-site repair services that save our customers time and hassle.": "تقديم خدمات إصلاح ميدانية سريعة وموثوقة واحترافية توفر على عملائنا الوقت والجهد.",
  "Customer First": "العميل أولاً",
  "We prioritize customer satisfaction above all else. Your trust is our most valuable asset, and we work hard to earn it every day.": "نضع رضا العميل فوق كل شيء. ثقتكم هي أهم ما لدينا، ونعمل يوميًا لنستحقها.",
  "Quality Guarantee": "ضمان الجودة",
  "We use only original or high-quality replacement parts and back all our repairs with a solid warranty for your peace of mind.": "نستخدم قطع غيار أصلية أو عالية الجودة، ونضمن جميع الإصلاحات بضمان قوي لراحة بالك.",
  "Our Guarantees": "ضماناتنا",
  "Free diagnosis when repair is approved": "فحص مجاني عند الموافقة على الإصلاح",
  "Original & high-quality spare parts": "قطع غيار أصلية وعالية الجودة",
  "3-6 months warranty on all repairs": "ضمان من 3 إلى 6 أشهر على جميع الإصلاحات",
  "Transparent pricing with no hidden fees": "تسعير شفاف بدون رسوم مخفية",
  "Same-day service for most repairs": "خدمة في نفس اليوم لمعظم الإصلاحات",
  "Money-back guarantee if not satisfied": "ضمان استرداد المال في حال عدم الرضا",
  Device: "الجهاز",
  Brand: "العلامة التجارية",
  Model: "الموديل",
  Issue: "المشكلة",
  Details: "التفاصيل",
  "Select Your Device": "اختر جهازك",
  "Add Another Device": "أضف جهازًا آخر",
  "Continue to Details": "المتابعة إلى التفاصيل",
  "One visit, all devices • Single tracking number • Priority scheduling": "زيارة واحدة لجميع الأجهزة • رقم تتبّع واحد • جدولة أولوية",
  "Continue with": "المتابعة مع",
  "Device(s)": "جهاز/أجهزة",
  "Devices Added": "الأجهزة المُضافة",
  "Select Brand": "اختر العلامة التجارية",
  "Select Model": "اختر الموديل",
  "Select Issue": "اختر المشكلة",
  "Book a": "احجز",
  Technician: "فني",
  "Select your device, tell us the problem, and we'll send a certified technician to your location.": "اختر جهازك، وأخبرنا بالمشكلة، وسنرسل فنيًا معتمدًا إلى موقعك.",
  Type: "النوع",
  "Your Details": "بياناتك",
  "Full Name *": "الاسم الكامل *",
  "Phone Number *": "رقم الهاتف *",
  WhatsApp: "واتساب",
  Address: "العنوان",
  "Address / Location *": "العنوان / الموقع *",
  "Preferred Date": "التاريخ المفضل",
  "Preferred Time": "الوقت المفضل",
  "Select time": "اختر الوقت",
  "Morning (9AM - 12PM)": "الصباح (9 صباحًا - 12 ظهرًا)",
  "Afternoon (12PM - 5PM)": "بعد الظهر (12 ظهرًا - 5 مساءً)",
  "Evening (5PM - 9PM)": "المساء (5 مساءً - 9 مساءً)",
  "As Soon As Possible": "في أسرع وقت ممكن",
  "Additional Notes": "ملاحظات إضافية",
  "Your full name": "اسمك الكامل",
  "WhatsApp number (optional)": "رقم واتساب (اختياري)",
  "Your address in Abu Dhabi": "عنوانك في أبوظبي",
  "Describe the issue in more detail (optional)": "صف المشكلة بمزيد من التفصيل (اختياري)",
  "Order Created Successfully!": "تم إنشاء الطلب بنجاح!",
  "Your Tracking Number": "رقم التتبّع الخاص بك",
  "Track Your Order": "تتبّع طلبك",
  "Chat on WhatsApp": "محادثة عبر واتساب",
  "Order Summary": "ملخص الطلب",
  "Add More": "أضف المزيد",
  "Create Order": "إنشاء الطلب",
  "By booking, you agree to our terms. Payment is only after successful repair.": "بالحجز، فإنك توافق على الشروط. الدفع فقط بعد إتمام الإصلاح بنجاح.",
  "Order Not Found": "لم يتم العثور على الطلب",
  "We couldn't find an order with tracking number": "لم نعثر على طلب برقم التتبّع",
  "Please check and try again.": "يرجى التحقق والمحاولة مرة أخرى.",
  "Contact Support": "تواصل مع الدعم",
  "Hotline 24/7": "الخط الساخن 24/7",
  "Abu Dhabi, UAE": "أبوظبي، الإمارات",
  "Tracking Number": "رقم التتبّع",
  "Order Date": "تاريخ الطلب",
  "Order Status": "حالة الطلب",
  "Order Created": "تم إنشاء الطلب",
  "Technician Assigned": "تم تعيين فني",
  "Technician On the Way": "الفني في الطريق",
  "Diagnostic in Progress": "جاري الفحص",
  "Repair in Progress": "جاري الإصلاح",
  "Quality Check": "فحص الجودة",
  "Completed / Delivered": "مكتمل / تم التسليم",
  "Mobile Phone": "هاتف محمول",
  Laptop: "لابتوب",
  "PC / Desktop Computer": "جهاز كمبيوتر مكتبي",
  "iPad / Tablet": "جهاز لوحي / آيباد",
  TV: "تلفزيون",
  CCTV: "كاميرات مراقبة",
  "PlayStation / Xbox": "أجهزة ألعاب",
  "Screen Replacement": "استبدال الشاشة",
  "Battery Replacement": "استبدال البطارية",
  "Charging Port Repair": "إصلاح منفذ الشحن",
  "Camera Replacement": "استبدال الكاميرا",
  "Speaker / Mic Fix": "إصلاح السماعة/الميكروفون",
  "Software Issues": "مشاكل برمجية",
  "Software / System Issue": "مشكلة في النظام/البرمجيات",
  "Software / System Issues": "مشاكل النظام/البرمجيات",
  "Water Damage": "أضرار المياه",
  "Back Glass Replacement": "استبدال الزجاج الخلفي",
  "Fan Cleaning & Thermal Paste": "تنظيف المروحة وتغيير المعجون الحراري",
  "Keyboard Replacement": "استبدال لوحة المفاتيح",
  "USB / HDMI Port Repair": "إصلاح منافذ USB/HDMI",
  "HDMI Port Repair": "إصلاح منفذ HDMI",
  "Windows Installation": "تثبيت ويندوز",
  "Overheating Fix": "حل مشكلة السخونة الزائدة",
  "SSD Upgrade": "ترقية SSD",
  "SSD/RAM Upgrade": "ترقية SSD/RAM",
  "Motherboard Repair": "إصلاح اللوحة الأم",
  "Sound Issues": "مشاكل الصوت",
  "Backlight Issues": "مشاكل الإضاءة الخلفية",
  "Backlight Repair": "إصلاح الإضاءة الخلفية",
  "Flickering / No Display": "وميض/لا توجد صورة",
  "Dead Pixels": "نقاط ميتة",
  "Color Calibration": "معايرة الألوان",
  "Power Issues": "مشاكل الطاقة",
  "TV Not Turning On": "التلفزيون لا يعمل",
  "Lines on Screen": "خطوط على الشاشة",
  "Full CCTV Installation": "تركيب كامل لنظام المراقبة",
  "DVR / NVR Setup": "إعداد DVR/NVR",
  "Camera Not Working": "الكاميرا لا تعمل",
  "No Signal": "لا توجد إشارة",
  "Night Vision Issues": "مشاكل الرؤية الليلية",
  "WiFi / Connectivity Fix": "حل مشاكل الاتصال/واي فاي",
  "Add New Cameras": "إضافة كاميرات جديدة",
  "Camera Upgrade": "ترقية الكاميرات",
  "TV Wall Mount Installation": "تركيب التلفزيون على الحائط",
  "Smart TV Setup": "إعداد التلفزيون الذكي",
  "Cable Management": "تنظيم الكابلات",
  "Soundbar Installation": "تركيب مكبر الصوت",
  "Full Home Theater Setup": "إعداد كامل لنظام المسرح المنزلي",
  "Controller Sync Issues": "مشاكل مزامنة جهاز التحكم",
  "Disc Drive Repair": "إصلاح محرك الأقراص",
  "Crown Repair": "إصلاح التاج الرقمي",
  "Sensor Issues": "مشاكل المستشعرات",
  "Pairing Issues": "مشاكل الاقتران",
  "Other Model (Enter Manually)": "موديل آخر (أدخل يدويًا)",
  "Enter Model Name": "أدخل اسم الموديل",
  "Use This Model": "استخدام هذا الموديل",
  Dashboard: "الرئيسية",
  "Dashboard Overview": "نظرة عامة",
  "Orders Management": "إدارة الطلبات",
  Technicians: "الفنيين",
  "Technicians Management": "إدارة الفنيين",
  "New Technician": "فني جديد",
  "Technician Details": "تفاصيل الفني",
  "Devices & Models & Issues": "الأجهزة والموديلات والمشاكل",
  "Contact Us Management": "إدارة التواصل",
  "Contact Messages": "رسائل التواصل",
  "Site Settings": "إعدادات الموقع",
  "Pages Content": "محتوى الصفحات",
  "Total Orders": "إجمالي الطلبات",
  "Orders In Progress": "طلبات قيد التنفيذ",
  "Completed Orders": "طلبات مكتملة",
  "Technicians Count": "عدد الفنيين",
  "Devices Supported": "الأجهزة المدعومة",
  "Today's New Orders": "طلبات جديدة اليوم",
  "Search": "بحث",
  "Filter by status": "تصفية حسب الحالة",
  "New Order": "طلب جديد",
  "Order ID": "رقم الطلب",
  "Customer Name": "اسم العميل",
  Phone: "الهاتف",
  "Issue Type": "نوع المشكلة",
  "Current Status": "الحالة الحالية",
  "Remaining Time": "الوقت المتبقي",
  "Assigned Technician": "الفني المعين",
  View: "عرض",
  Edit: "تعديل",
  Save: "حفظ",
  Cancel: "إلغاء",
  All: "الكل",
  "Order Details": "تفاصيل الطلب",
  Customer: "العميل",
  "Device Details": "تفاصيل الجهاز",
  "ETA (minutes)": "المدة المتوقعة (دقائق)",
  Notes: "ملاحظات",
  Price: "السعر",
  Discount: "خصم",
  Total: "الإجمالي",
  "View / Edit Order": "عرض / تعديل الطلب",
  "Change order status": "تغيير حالة الطلب",
  "Modify estimated completion time": "تعديل وقت الإتمام المتوقع",
  "Assign a technician": "تعيين فني",
  "View customer details": "عرض تفاصيل العميل",
  "View device details": "عرض تفاصيل الجهاز",
  "Edit manual info": "تعديل المعلومات يدويًا",
  "Save updates": "حفظ التحديثات",
  Name: "الاسم",
  Specialization: "التخصص",
  Status: "الحالة",
  Active: "نشط",
  Inactive: "غير نشط",
  "Current assigned jobs": "الأعمال الحالية",
  Add: "إضافة",
  Delete: "حذف",
  Update: "تحديث",
  "Devices List": "قائمة الأجهزة",
  "Models Management": "إدارة الموديلات",
  "Issues Management": "إدارة المشاكل",
  "Enable Other Model (Enter Manually)": "تفعيل موديل آخر (إدخال يدوي)",
  "Model Year Range": "نطاق سنة الموديل",
  "Contact Settings": "إعدادات التواصل",
  "Main Email": "البريد الإلكتروني الرئيسي",
  "WhatsApp Number": "رقم واتساب",
  "Support Phone Number": "رقم دعم العملاء",
  "Secondary Phone (optional)": "رقم إضافي (اختياري)",
  "Business Address": "عنوان العمل",
  "Working Hours": "ساعات العمل",
  "Service Areas": "مناطق الخدمة",
  "Save Settings": "حفظ الإعدادات",
  "Settings saved": "تم حفظ الإعدادات",
  
  Email: "البريد الإلكتروني",
  Subject: "الموضوع",
  Date: "التاريخ",
  StatusText: "الحالة",
  New: "جديد",
  Read: "مقروء",
  "View Message": "عرض الرسالة",
  "Message Body": "نص الرسالة",
  "Mark as Read": "وضع كمقروء",
  "Delete Message": "حذف الرسالة",
  "Business Name": "اسم العمل",
  "Main Phone": "الهاتف الرئيسي",
  "WhatsApp Link": "رابط واتساب",
  
  "Footer Text": "نص التذييل",
  "Social Media Links": "روابط التواصل الاجتماعي",
  "Enable Digital Countdown": "تفعيل العد التنازلي الرقمي",
  "Enable Corporate Page": "تفعيل صفحة الشركات",
  "Pages Content Editor": "محرر محتوى الصفحات",
  "Home Page": "الصفحة الرئيسية",
  "Services Page": "صفحة الخدمات",
  "Corporate Services Page": "صفحة خدمات الشركات",
  "About Page": "صفحة من نحن",
  "Call-to-action Text": "نص الدعوة للإجراء",
  "Hardware: Power Supply Issue": "عطل مزوّد الطاقة",
  "Hardware: No Display": "لا توجد صورة",
  "Hardware: Overheating": "سخونة زائدة",
  "Hardware: CPU Fan Replacement": "استبدال مروحة المعالج",
  "Hardware: RAM Upgrade / Replacement": "ترقية/استبدال الذاكرة",
  "Hardware: SSD Upgrade / OS Install": "ترقية SSD / تثبيت النظام",
  "Hardware: GPU Issue / No Signal": "مشكلة بطاقة الرسومات/لا توجد إشارة",
  "Hardware: Motherboard Repair": "إصلاح اللوحة الأم",
  "Software: Windows Installation": "تثبيت ويندوز",
  "Software: Virus Removal": "إزالة الفيروسات",
  "Software: System Slow": "بطء النظام",
  "Software: Driver Issues": "مشاكل التعريفات",
  "Software: BIOS Errors": "أخطاء BIOS",
  "Physical: Broken Ports (USB / HDMI)": "منافذ تالفة (USB/HDMI)",
  "Physical: Front Panel Not Working": "المنافذ الأمامية لا تعمل",
  "Physical: PSU Noise": "ضجيج مزوّد الطاقة",
  "Seed Default Data": "تعبئة البيانات الافتراضية",
  "Device Icon": "أيقونة الجهاز",
  "Device Name": "اسم الجهاز",
  
  "Upload an icon or a default placeholder will be used.": "قم برفع أيقونة، أو سيتم استخدام أيقونة افتراضية.",
  "Select Device": "اختر الجهاز",
  "New Brand Name": "اسم علامة جديد",
  "No brands found": "لا توجد علامات",
  "Brands Management": "إدارة العلامات",
  "Adding models for:": "إضافة موديلات لـ:",
  "New Model Name": "اسم موديل جديد",
  "No models found": "لا توجد موديلات",
  "Select a brand to manage models": "اختر علامة لإدارة الموديلات",
  "Issue Name": "اسم المشكلة",
  "Mins": "دقائق",
  "Duration:": "المدة:",
  "min": "دقيقة",
  "No issues found for this device": "لا توجد مشاكل لهذا الجهاز",
  "Time Remaining": "الوقت المتبقي",
  "e.g. Screen Replacement": "مثال: استبدال الشاشة",
  "Technician Dashboard": "لوحة تحكم الفني",
  "Active Jobs": "المهام النشطة",
  "Assigned Orders": "الطلبات المعينة",
  "My Profile": "ملفي الشخصي",
  "Welcome back": "مرحبًا بعودتك",
  "View All Orders": "عرض كل الطلبات",
  "Completed Today": "المكتملة اليوم",
  "Total Assigned": "إجمالي المعين",
  "Lifetime orders": "كل الطلبات",
  "Recent Assigned Orders": "آخر الطلبات المعينة",
  "Loading orders...": "جاري تحميل الطلبات...",
  "No orders assigned yet.": "لا توجد طلبات معينة بعد.",
  "Manage your daily tasks": "إدارة مهامك اليومية",
  "Search by ID, Device, Customer...": "بحث بالرقم، الجهاز، العميل...",
  "Filter by Status": "تصفية حسب الحالة",
  "All Statuses": "كل الحالات",
  "No orders found matching your criteria.": "لا توجد طلبات تطابق بحثك.",
  "Assigned to you": "معين لك",
  "Navigate": "الملاحة",
  "Update Order Status": "تحديث حالة الطلب",
  "Select new status": "اختر الحالة الجديدة",
  "Waiting for Parts": "بانتظار قطع الغيار",
  "Work Notes": "ملاحظات العمل",
  "Add a note...": "أضف ملاحظة...",
  "Attachments": "المرفقات",
  "Sign Out": "تسجيل الخروج",
  "Average Rating": "متوسط التقييم",
  "Jobs Completed": "المهام المكتملة",
  "Specializations": "التخصصات",
  "Account Info": "معلومات الحساب",
  "Member Since": "عضو منذ",
  "Employee ID": "رقم الموظف",
  
  "Export CSV": "تصدير CSV",
  "Search orders...": "بحث عن الطلبات...",
  
  "Waiting Parts": "بانتظار القطع",
  "Delivered": "تم التسليم",
  "Cancelled": "ملغى",
  "Actions": "إجراءات",
  "Open menu": "فتح القائمة",
  "View Details": "عرض التفاصيل",
  "Assign Technician": "تعيين فني",
  "Delete Order": "حذف الطلب",
  "Previous": "السابق",
  "Next": "التالي",
  "Page": "صفحة",
  "of": "من",
  
  "Created": "تم الإنشاء",
  
  "No orders found": "لا توجد طلبات",
  "Unassigned": "غير معيّن",
  "Order Timeline": "الخط الزمني للطلب",
  "Order Placed": "تم إنشاء الطلب",
  "Order has been created": "تم إنشاء الطلب",
  "In Repair": "قيد الإصلاح",
  "Technician is working on the device": "الفني يعمل على الجهاز",
  "Repair Completed": "تم إكمال الإصلاح",
  "Device returned to customer": "تم تسليم الجهاز للعميل",
  "Order Cancelled": "تم إلغاء الطلب",
  "This order has been cancelled.": "هذا الطلب تم إلغاؤه.",
  "Detailed History": "سجل تفصيلي",
  "Just now": "الآن",
  "Pending": "قيد الانتظار",
  "In Progress": "قيد التنفيذ",
  "Orders": "الطلبات",
  "Inventory": "المخزون",
  "Contact Inbox": "البريد الوارد للتواصل",
  "Corporate Requests": "طلبات الشركات",
  "Settings": "الإعدادات",
  "Management": "الإدارة",
  "Inbox": "البريد الوارد",
  "Configuration": "التهيئة",
  "Admin Panel": "لوحة الإدارة",
  "Repair Services": "خدمات الإصلاح",
  "Admin User": "مستخدم الإدارة",
  "Technician Portal": "بوابة الفني",
  "Log out": "تسجيل الخروج",
  "Profile": "الملف الشخصي",
  "Add Technician": "إضافة فني",
  "Add New Technician": "إضافة فني جديد",
  "Enter technician details and permissions": "أدخل بيانات الفني والصلاحيات",
  "Update technician details and permissions": "تحديث بيانات الفني والصلاحيات",
  "Specialization (comma separated)": "التخصصات (مفصولة بفواصل)",
  
  "Save Changes": "حفظ التغييرات",
  "No technicians found": "لا يوجد فنيون",
  "Permissions": "الصلاحيات",
  "Messages": "الرسائل",
  
  "No messages": "لا توجد رسائل",
  "Select a message to read": "اختر رسالة لقراءتها",
  "Delete this message?": "هل تريد حذف هذه الرسالة؟",
  "Contact Information": "معلومات التواصل",
  "Email Address": "عنوان البريد الإلكتروني",
  "Phone Number": "رقم الهاتف",
  "Error saving settings": "خطأ في حفظ الإعدادات",
  "Status updated to": "تم تحديث الحالة إلى",
  "Assigned to technician": "تم تعيين الفني",
  "Device is fixed and ready": "الجهاز جاهز ومُصلح",
  "Are you sure you want to delete this technician?": "هل أنت متأكد من حذف هذا الفني؟",
  "Are you sure you want to delete this order?": "هل أنت متأكد من حذف هذا الطلب؟",
  "Delete this request?": "هل تريد حذف هذا الطلب؟",
  "No requests": "لا توجد طلبات",
  "Contacted": "تم التواصل",
  "Closed": "مغلق",
  "Mark Contacted": "وضع كمتواصل",
  "Close Request": "إغلاق الطلب",
  "Message": "الرسالة",
  "Select a request to view details": "اختر طلبًا لعرض التفاصيل",
  "Contact:": "جهة الاتصال:",
  "Devices:": "الأجهزة:",
  "Request Received": "تم استلام الطلب",
  "Thank you for choosing KBI Corporate. Our enterprise team has received your request and will contact you within 2 hours.": "شكرًا لاختيارك KBI للشركات. لقد استلم فريقنا طلبك وسيتواصل معك خلال ساعتين.",
  "Company Name": "اسم الشركة",
  "Company Email": "البريد الإلكتروني للشركة",
  "Contact Person": "جهة الاتصال",
  "Mobile Number": "رقم الجوال",
  "Location": "الموقع",
  "Device Count": "عدد الأجهزة",
  "Device Types": "أنواع الأجهزة",
  "Urgency": "درجة الأهمية",
  "Select Urgency Level": "اختر درجة الأهمية",
  "Normal (24-48h)": "عادي (24-48 ساعة)",
  "High (Same Day)": "عالي (نفس اليوم)",
  "Critical (Immediate - 2h)": "حرِج (فوري - 2 ساعة)",
  "Office Location / Area": "موقع المكتب / المنطقة",
  "Approx. number of devices": "العدد التقريبي للأجهزة",
  "Phones, Laptops, PC / Desktop, Printers, CCTV, TVs": "هواتف، لابتوبات، كمبيوتر مكتبي، طابعات، كاميرات مراقبة، تلفزيونات",
  "Full Name": "الاسم الكامل",
  "e.g. Tech Solutions Ltd": "مثال: شركة تك سوليوشنز",
  "e.g. Tomorrow 10AM": "مثال: غدًا الساعة 10 صباحًا",
  "Submit Request": "إرسال الطلب",
  "Request Additional Parts / Services": "طلب إضافة قطع/خدمات",
  "Part / Service Name": "اسم القطعة/الخدمة",
  "Category": "الفئة",
  "Spare Part": "قطعة غيار",
  "Additional Service": "خدمة إضافية",
  "Quantity": "الكمية",
  "Estimated Price (AED)": "السعر التقديري (درهم)",
  "Reason for Request": "سبب الطلب",
  "Optional Photo": "صورة اختيارية",
  "Pending Admin Approval": "بانتظار موافقة الإدارة",
  "Technician Requests": "طلبات الفنيين",
  "Approve Request": "الموافقة على الطلب",
  "Reject Request": "رفض الطلب",
  "Edit Price": "تعديل السعر",
  "Admin Notes": "ملاحظات الإدارة",
  "Request approved": "تمت الموافقة على الطلب",
  "Request rejected": "تم رفض الطلب",
  "Price updated by admin": "تم تحديث السعر بواسطة الإدارة",
  "New technician request submitted": "تم إرسال طلب جديد من الفني",
  "Waiting for Parts Approval": "بانتظار موافقة القطع",
  "Approved – Continue Repair": "تمت الموافقة – متابعة الإصلاح",
  "Notifications": "الإشعارات",
  "No notifications": "لا توجد إشعارات",
  "Invoice": "الفاتورة",
  "On-Site Repair Service": "خدمة الإصلاح في الموقع",
  "Invoice Number": "رقم الفاتورة",
  "Invoice Date": "تاريخ الفاتورة",
  "Customer Information": "بيانات العميل",
  "Service Address": "عنوان الخدمة",
  "Device Information": "بيانات الجهاز",
  "Device Type": "نوع الجهاز",
  "Serial Number (optional)": "الرقم التسلسلي (اختياري)",
  "Description": "الوصف",
  "Qty": "الكمية",
  "Unit Price (AED)": "سعر الوحدة (درهم)",
  "Total (AED)": "الإجمالي (درهم)",
  "Subtotal": "المجموع الفرعي",
  "VAT": "ضريبة القيمة المضافة",
  "Final Total Price (AED)": "الإجمالي النهائي (درهم)",
  "Warranty & Notes": "الضمان والملاحظات",
  "Warranty Period": "مدة الضمان",
  "Thank you for choosing KBI.": "شكرًا لاختيارك KBI.",
  "Customer Signature": "توقيع العميل",
  "Technician Signature": "توقيع الفني",
  "Generate Final Invoice": "إنشاء الفاتورة النهائية",
  "Preview Invoice": "معاينة الفاتورة",
  "Print Invoice": "طباعة الفاتورة",
  "Download as PDF": "تحميل كملف PDF",
  "Resend to Customer": "إعادة الإرسال إلى العميل",
  "Invoice Status": "حالة الفاتورة",
  "Finalize Invoice": "اعتماد الفاتورة",
  "Override reason": "سبب التعديل",
  "Override Edit": "تعديل بالإلغاء",
  "English": "الإنجليزية",
  "Arabic": "العربية",
  "EN + AR": "العربية + الإنجليزية",
  "Invoice Preview": "معاينة الفاتورة",
  "VAT Enabled": "تشغيل الضريبة",
  "VAT Rate": "نسبة الضريبة",
  "Disclaimer": "إخلاء المسؤولية"
  
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en")

  useEffect(() => {
    if (typeof window === "undefined") return
    const stored = window.localStorage.getItem("kbi-lang") as Lang | null
    if (stored && stored !== lang) setLang(stored)
  }, [])

  useEffect(() => {
    if (typeof document === "undefined") return
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
    if (typeof window !== "undefined") {
      window.localStorage.setItem("kbi-lang", lang)
    }
  }, [lang])

  useEffect(() => {
    if (typeof window === "undefined") return
    let triggered = false
    const reload = () => {
      if (triggered) return
      triggered = true
      try {
        const c = (window as any).caches
        if (c && c.keys) {
          c
            .keys()
            .then((keys: string[]) => {
              for (const k of keys) c.delete(k).catch(() => {})
            })
            .catch(() => {})
        }
      } catch { void 0 }
      window.location.reload()
    }
    const onError = (e: Event) => {
      const t = e.target as any
      const isScript = t && (t.tagName === "SCRIPT" || t.localName === "script")
      const src = isScript ? t.src || "" : ""
      if (isScript && /:\/\/localhost:8081\/.*/.test(src)) {
        try { e.preventDefault() } catch { void 0 }
        return
      }
      if (isScript && src.includes("/_next/static/")) reload()
    }
    const onRejection = (e: PromiseRejectionEvent) => {
      const name = e.reason?.name || ""
      const msg = String(e.reason?.message || "")
      const isAbort = name === "AbortError" || /ERR_ABORTED/i.test(msg) || /\?_rsc=/.test(msg)
      if (isAbort) {
        try { e.preventDefault() } catch { void 0 }
        return
      }
      if (name === "ChunkLoadError" || /Loading chunk .* failed/i.test(msg)) reload()
    }
    window.addEventListener("error", onError, true)
    window.addEventListener("unhandledrejection", onRejection)
    return () => {
      window.removeEventListener("error", onError, true)
      window.removeEventListener("unhandledrejection", onRejection)
    }
  }, [])

  const value = useMemo(() => ({ lang, setLang }), [lang])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}

export function useT() {
  const { lang } = useLanguage()
  return (key: string) => (lang === "ar" ? DICTIONARY[key] || key : key)
}
